language: python
install: pip install tox --use-mirrors
env:
  - TOX_ENV=py27
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pep8
  - TOX_ENV=pypy

script: tox -e $TOX_ENV
notifications:
  email:
    - swistakm@gmail.com
